### PR TITLE
Zigbee

### PR DESCRIPTION
**Pull request by tomaszduda23**
# What does this implement/fix?

zigbee support

Screenshot from 2024-06-05 21-12-08

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>
https://github.com/esphome/feature-requests/issues/1397

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
switch:
  - platform: zigbee
    output: gpio_15
    id: zigbee1
  - platform: zigbee
    output: gpio_15
    id: zigbee2

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by lboue** [comment]
I was unable to compile with the configuration provided. Did I miss something?

**ESPHome config**

```
external_components:
  - source:
      type: git
      url: https://github.com/tomaszduda23/esphome/
      ref: zigbee
    refresh: 0s
    components: 
      - zephyr_mcumgr/ota
      - zephyr_shell
      - zigbee/switch

switch:
  - platform: zigbee
    output: gpio_15
    id: zigbee1

zephyr_shell:
```

**ESPHome build log**

```
INFO ESPHome 2024.8.0-dev
INFO Reading configuration /config/esphome/zigbee-test.yaml...
INFO Updating https://github.com/tomaszduda23/esphome/@zigbee
INFO Unable to import component zigbee.switch: No module named 'esphome.components.zigbee'
Failed config

switch.zigbee: [source /config/esphome/zigbee-test.yaml:48]
  
  Platform not found: 'switch.zigbee'.
  platform: zigbee
  output: gpio_15
  id: zigbee1
```

**Comment by tomaszduda23** [comment]
This requires nrf52840 which cannot be used as external component. Waiting for https://github.com/esphome/esphome/pull/7049

**Comment by Hedda** [comment]
Espressif developer P-R-O-C-H-Y is now working on a new Zigbee Wrapper library with a simpler API in Arduino (for arduino-esp32) and he wrote that other developers can post additional feature request related to that in the same issue there for tracking. Maybe you could port that for nrf52 so could make use of the same Zigbee API that will probably be used for ESP32's Zigbee?

* https://github.com/espressif/arduino-esp32/issues/10135

**Comment by tomaszduda23** [comment]
PR for this was already opened in main repo https://github.com/esphome/esphome/pull/7340

**Pull request closed without merging**
